# Generated by Django 4.2.6 on 2023-10-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='money',
            field=models.CharField(default=1, max_length=255, verbose_name='Зарплата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='oclock',
            field=models.CharField(default=1, max_length=255, verbose_name='Часы работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='work',
            field=models.CharField(default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
